// <auto-generated />
namespace EntityData.Migrations.DataDBContextNS
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddBarDTOpen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBarDTOpen));
        
        string IMigrationMetadata.Id
        {
            get { return "201404201506394_AddBarDTOpen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
