// <auto-generated />
namespace EntityData.Migrations.DataDBContextNS
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndexFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndexFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201609140220190_IndexFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
