// <auto-generated />
namespace EntityData.Migrations.DataDBContextNS
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class DataInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201401201826336_DataInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
